#!/bin/bash --login
#PBS -l walltime=01:30:00
#PBS -l select=1:ncpus=32
#PBS -N PCoA_2D
#PBS -A d411-training

cd $PBS_O_WORKDIR

export TMPDIR=~/qiime_temp

module load miniconda/python2

echo "loading virtualenv"

source activate qiime1

echo "Make 2-D PCoA Plot"

time make_2d_plots.py -i ~/core_diversity/bdiv_even627/weighted_unifrac_pc.txt -m ~/2018_02_smb/map.complete.tsv -b SampleNitrogen -o ~2d_pcoa/

source deactivate
