#!/bin/bash --login
#PBS -l walltime=01:30:00
#PBS -l select=1:ncpus=32
#PBS -N corediversityanalyses_taxafiltered
#PBS -A d411-training

cd $PBS_O_WORKDIR

export TMPDIR=~/qiime_temp

module load miniconda/python2

echo "loading virtualenv"

source activate qiime1

echo "Core Diversity Analysis"

time core_diversity_analyses.py -i ~/taxonomyfiltered.biom -m ~/2018_02_smb/map.complete.tsv -t ~/SILVA_132_QIIME_release/trees/99/99_otus.tre -o ~/core_diversity_taxafiltered -e 647 -c SampleNitrogen -a -O 16

source deactivate
