#!/bin/bash --login
#PBS -l walltime=01:30:00
#PBS -l select=1:ncpus=32
#PBS -N comparecategories
#PBS -A d411-training

cd $PBS_O_WORKDIR

export TMPDIR=~/qiime_temp

module load miniconda/python2

echo "loading virtualenv"

source activate qiime1

echo "Compare Categories"

time compare_categories.py --method anosim -i ~/core_diversity_taxafiltered/bdiv_even647/weighted_unifrac_dm.txt -m ~/2018_02_smb/map.complete.tsv -c SampleNitrogen -o anosim_category_test_taxafiltered -n 999

source deactivate
