#!/bin/bash --login
#PBS -l walltime=01:30:00
#PBS -l select=1:ncpus=4
#PBS -N 2018_demultiplex
#PBS -A d411-training

cd $PBS_O_WORKDIR
export TMPDIR=~/qiime_tmp
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
echo "splitting libraries"
time split_libraries_fastq.py --barcode_type 12\
 -i ~/2018_02_smb/fastq-join_joined/seqprep_assembled.fastq.gz\
 -o ~/split_libraries\
 -b ~/2018_02_smb/fastq-join_joined/seqprep_assembled.fastq_barcodes.fastq\
 -m ~/2018_02_smb/map.complete.tsv\
 -q 19\
 --rev_comp_barcode\
 --rev_comp_mapping_barcodes
 
source deactivate
