#!/bin/bash --login
#PBS -l walltime=01:30:00
#PBS -l select=1:ncpus=32
#PBS -N nitrogensignificance
#PBS -A d411-training

cd $PBS_O_WORKDIR

export TMPDIR=~/qiime_temp

module load miniconda/python2

echo "loading virtualenv"

source activate qiime1

echo "Group significance using Kruskal Wallis Test"

time group_significance.py -i ~/core_diversity_taxafiltered/taxa_plots/table_mc647_sorted_L3.biom -m ~/2018_02_smb/map.complete.tsv -c SampleNitrogen -o ~/Nitrogen_group_significance 

source deactivate
