#!/bin/bash --login
#PBS -l walltime=01:30:00
#PBS -l select=1:ncpus=32
#PBS -N heatmap
#PBS -A d411-training

cd $PBS_O_WORKDIR

export TMPDIR=~/qiime_temp

module load miniconda/python2

echo "loading virtualenv"

source activate qiime1

echo "Make Heat Map From Filtered OTU Table"

time make_otu_heatmap.py -i ~/core_diversity_taxafiltered/taxa_plots/table_mc647_sorted_L3.biom -c SampleNitrogen -o ~/heatmap.pdf --suppress_row_clustering --suppress_column_clustering --color_scheme PuBu

source deactivate
