#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=4
#PBS -N bioc3301_2018_join
#PBS -A d411-training

cd $PBS_O_WORKDIR

# setting temporary directory
export TMPDIR=~/qiime_tmp

module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"
# NB qiime1 and not qiime1
source activate qiime1

#join paired ends
echo "join paired ends"
join_paired_ends.py -m SeqPrep -f ~/2018_02_smb/Read1.fastq.gz -r ~/2018_02_smb/Read2.fastq.gz -b ~/2018_02_smb/Index.fastq.gz -o ~/2018_02_smb/fastq-join_joined

source deactivate
