#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=32
#PBS -N OTUs
#PBS -A d411-training

cd $PBS_O_WORKDIR

export TMPDIR=~/qiime_temp

module load miniconda/python2

echo "loading virtualenv"

source activate qiime1

echo "Picking OTUs with closed reference"

time pick_closed_reference_otus.py -i split_libraries/seqs.fna -o otus -a -O 16

source deactivate
