#!/bin/bash --login
#PBS -l walltime=01:30:00
#PBS -l select=1:ncpus=32
#PBS -N Filtertaxa
#PBS -A d411-training

cd $PBS_O_WORKDIR

export TMPDIR=~/qiime_temp

module load miniconda/python2

echo "loading virtualenv"

source activate qiime1

echo "Filter Taxonomy from OTU table"

time filter_taxa_from_otu_table.py -i ~/otus/otu_table.biom -o ~/taxonomyfiltered.biom -p D_1__Thaumarchaeota,D_1__Proteobacteria

source deactivate
